language: r
cache: packages
warnings_are_errors: false
dist: trusty
sudo: required
env:
  - R_CODECOV=true
  - R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

before_install:
  # Update C++ compiler to a C++11 compatible one, while still
  # mantaining the ability to link gfortran code.  From:
  # http://gearchicken.com/wordpress/?p=105
  # http://askubuntu.com.80bola.com/questions/612591/usr-bin-ld-cannot-find-lgfortran-matlab
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq install g++-4.9 libgfortran3-dbg
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/x86_64-linux-gnu/libgfortran.so
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

r_github_packages:
  - richfitz/RcppR6
  - richfitz/grader
  - smbache/loggr
  - jimhester/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack: bdkd:DPfom03G2FgVC9z69XMi9g4L
